[package]
name = "zkp-chaum-pedersen"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
num-bigint = { version = "0.4.6", features = ["rand"]}
rand = "0.8.5"

[build-dependencies]
tonic-build = "0.9"
